server:
  port: 8011

spring:
  application:
    name: service-order
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://yangfan.cool:54321/postgres
    username: postgres
    password: cs304_se_1113
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848