server:
  port: 8051

spring:
  application:
    name: service-eval
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: txl20020705@
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848